Fix locale-dependent failure in ErrorSituationsDuringSlimServerStartup
The test fails because the exception message is localized. For example
when running with LANG=de_DE.UTF-8 the message is:

java.net.BindException: Die Adresse wird bereits verwendet (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)

(which is German for "Address already in use")

It seems that there is no way to get the non-localized message:
https://stackoverflow.com/questions/17159357/is-there-a-way-to-force-exception-message-to-be-english-for-java-1-7